.TH "ADC.h" 3 "Sun Jun 19 2011" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <LPC23xx.H>\fP
.br
\fC#include <stdint.h>\fP
.br
\fC#include <stdarg.h>\fP
.br
\fC#include <stdio.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBADC\fP"
.br
.RI "\fIclass \fBADC\fP: is a class in charge of \fBADC\fP channels from 0 to 7 of ARM 7 processor. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBADC_OFFSET\fP   0x10"
.br
.ti -1c
.RI "#define \fBADC_INDEX\fP   4"
.br
.ti -1c
.RI "#define \fBADC_DONE\fP   0x80000000"
.br
.ti -1c
.RI "#define \fBADC_OVERRUN\fP   0x40000000"
.br
.ti -1c
.RI "#define \fBADC_ADINT\fP   0x00010000"
.br
.ti -1c
.RI "#define \fBADC_NUM\fP   8"
.br
.ti -1c
.RI "#define \fBADC_CLK\fP   1000000"
.br
.ti -1c
.RI "#define \fBFpclk\fP   12000000"
.br
.ti -1c
.RI "#define \fBADC_Clk\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ADC_ADINT   0x00010000"
.SS "#define ADC_Clk"
.SS "#define ADC_CLK   1000000"
.SS "#define ADC_DONE   0x80000000"
.SS "#define ADC_INDEX   4"
.SS "#define ADC_NUM   8"
.SS "#define ADC_OFFSET   0x10"
.SS "#define ADC_OVERRUN   0x40000000"
.SS "#define Fpclk   12000000"
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
