.TH "Buzzer.cpp" 3 "Sun Jun 19 2011" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Buzzer.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Buzzer.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBbuzzFRQCounter\fP"
.br
.ti -1c
.RI "\fBDAC\fP \fBbuzzerDAC\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBDAC\fP \fBbuzzerDAC\fP"
.SS "int \fBbuzzFRQCounter\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
