.TH "FastInterrupt.h" 3 "Sun Jun 19 2011" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FastInterrupt.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <LPC23xx.H>\fP
.br
\fC#include 'PortPin.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFastInterrupt\fP"
.br
.RI "\fIclass \fBFastInterrupt\fP: is a class in charge of \fBFastInterrupt\fP in ARM 7 processor it handels EXTINT0, EXTINT1, EXTINT2, EXTINT3. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBInterrupt_h\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfastInterruptHandler\fP (void) __irq"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define Interrupt_h"
.SH "Function Documentation"
.PP 
.SS "void fastInterruptHandler (void)"
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
