.TH "Keys" 3 "Sun Jun 26 2011" "Version 1.100.000" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Keys \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKey\fP"
.br
.RI "\fIclass \fBKey\fP: is a class provide methods which use to present keyboard keys. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int const \fBKey::ENTER\fP"
.br
.ti -1c
.RI "int const \fBKey::DELETE\fP"
.br
.ti -1c
.RI "int const \fBKey::BACKSPACE\fP"
.br
.ti -1c
.RI "int const \fBKey::SPACE\fP"
.br
.ti -1c
.RI "int const \fBKey::ESCAPE\fP"
.br
.ti -1c
.RI "int const \fBKey::F1\fP"
.br
.ti -1c
.RI "int const \fBKey::F2\fP"
.br
.ti -1c
.RI "int const \fBKey::F3\fP"
.br
.ti -1c
.RI "int const \fBKey::F4\fP"
.br
.ti -1c
.RI "int const \fBKey::F5\fP"
.br
.ti -1c
.RI "int const \fBKey::F6\fP"
.br
.ti -1c
.RI "int const \fBKey::F7\fP"
.br
.ti -1c
.RI "int const \fBKey::F8\fP"
.br
.ti -1c
.RI "int const \fBKey::F9\fP"
.br
.ti -1c
.RI "int const \fBKey::F10\fP"
.br
.ti -1c
.RI "int const \fBKey::F11\fP"
.br
.ti -1c
.RI "int const \fBKey::F12\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Keys 
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
