.TH "Port(GPIO) - Individual pin of ports" 3 "Sun Jun 26 2011" "Version 1.100.000" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Port(GPIO) - Individual pin of ports \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPortPin\fP"
.br
.RI "\fIclass \fBRealTimeClock\fP: is a class in charge of GPIO (Port 0,1,2,3,4) which is connected to ARM 7 processor.
.PP
/sa \fBInterrupt\fP \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPortPin::PortPin\fP (uint8_t newPortID, int newPinID, std::string IO, std::string initState)"
.br
.ti -1c
.RI "void \fBPortPin::on\fP (void)"
.br
.ti -1c
.RI "void \fBPortPin::off\fP (void)"
.br
.ti -1c
.RI "bool \fBPortPin::getPinValue\fP (void)"
.br
.ti -1c
.RI "int \fBPortPin::getPinNumber\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Port(GPIO) - Individual pin of ports 
.SH "Function Documentation"
.PP 
.SS "bool PortPin::getPinValue (void)"return the value of pin.
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIbool\fP bitStatus:
.IP "\(bu" 2
True: bit value is '1'
.IP "\(bu" 2
False: bit value is '0' 
.br

.PP
.RE
.PP
\fBExample:\fP
.br
.PP
\fBPortPin\fP pin10(2,10,'INPUT'); 
.br
 \fBPortPin\fP pin0(2,0,'OUTPUT','ON'); 
.br
 \fBPortPin\fP pin1(2,1,'OUTPUT','OFF'); 
.br
 if(pin10.getPinValue() )
.br
 { 
.br
 pin1.on(); 
.br
 } 
.br
 
.SS "void PortPin::off (void)"Set the pin value to 0.
.br
 
.br
.PP
\fBExample:\fP
.br
.PP
\fBPortPin\fP pin10(2,10,'INPUT'); 
.br
 \fBPortPin\fP pin0(2,0,'OUTPUT','ON'); 
.br
 \fBPortPin\fP pin1(2,1,'OUTPUT','OFF'); 
.br
 pino.off(); 
.br
 
.SS "void PortPin::on (void)"Set the pin value to 1.
.br
 
.br
.PP
\fBExample:\fP
.br
.PP
\fBPortPin\fP pin10(2,10,'INPUT'); 
.br
 \fBPortPin\fP pin0(2,0,'OUTPUT','ON'); 
.br
 \fBPortPin\fP pin1(2,1,'OUTPUT','OFF'); 
.br
 pin1.on(); 
.br
 
.SS "PortPin::PortPin (uint8_tnewPortID, intnewPinID, std::stringIO, std::stringinitState)"Second constructor: Initialize a PIN of any five availabel Port.
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIuint8_t\fP newPortID: Port number 
.br
 
.br
\fIint\fP newPinID: Pin number 
.br
 
.br
\fIstd::string\fP IO: set the IO status of pin 
.br
.IP "\(bu" 2
INPUT : set the pin as an input
.IP "\(bu" 2
OUTPUT : set the pin as an output 
.PP
.br
\fIstd::string\fP initState: set the initialize value of pin 
.br
.IP "\(bu" 2
ON : set pin to '1'
.IP "\(bu" 2
OFF: set pin to '0' 
.br

.PP
.RE
.PP
\fBExample:\fP
.br
.PP
\fBPortPin\fP pin10(2,10,'INPUT'); 
.br
 \fBPortPin\fP pin0(2,0,'OUTPUT','ON'); 
.br
 \fBPortPin\fP pin1(2,1,'OUTPUT','OFF'); 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
