.TH "TimerDelay" 3 "Tue Jun 21 2011" "Version 1.100.000" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimerDelay \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTimerDelay0\fP"
.br
.RI "\fIclass \fBTimerDelay0\fP: is a class which use to generate delay it uses timer0 of ARM7. \fP"
.ti -1c
.RI "class \fBTimerDelay1\fP"
.br
.RI "\fIclass \fBTimerDelay1\fP: is a class which use to generate delay it uses timer1 of ARM7. \fP"
.ti -1c
.RI "class \fBTimerDelay2\fP"
.br
.RI "\fIclass \fBTimerDelay2\fP: is a class which use to generate delay it uses timer2 of ARM7. \fP"
.ti -1c
.RI "class \fBTimerDelay3\fP"
.br
.RI "\fIclass \fBTimerDelay3\fP: is a class which use to generate delay it uses timer3 of ARM7. \fP"
.in -1c
.SH "Detailed Description"
.PP 
TimerDelay 
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
