.TH "Interrupt.h" 3 "Sun Jun 19 2011" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interrupt.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <LPC23xx.H>\fP
.br
\fC#include 'PortPin.h'\fP
.br
\fC#include 'RealTimeClock.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInterrupt\fP"
.br
.RI "\fIclass \fBInterrupt\fP: is a class in charge of \fBInterrupt\fP in ARM 7 processor it handels EXTINT0, EXTINT1, EXTINT2, EXTINT3. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPREINT_RTC\fP   0x000001C8"
.br
.ti -1c
.RI "#define \fBPREFRAC_RTC\fP   0x000061C0"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define PREFRAC_RTC   0x000061C0"
.SS "#define PREINT_RTC   0x000001C8"
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
