.TH "RTA_Config.c" 3 "Sun Jun 19 2011" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTA_Config.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <RT_Agent.c>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB__RTA_ENABLED\fP   1"
.br
.ti -1c
.RI "#define \fBRTA_HW_LPC21xx\fP   1"
.br
.ti -1c
.RI "#define \fBRTA_HW_LPC23xx\fP   2"
.br
.ti -1c
.RI "#define \fBRTA_HW_STR91x\fP   3"
.br
.ti -1c
.RI "#define \fBRTA_HW_AT91SAM7Sx\fP   4"
.br
.ti -1c
.RI "#define \fBRTA_HW_POLLED\fP   99"
.br
.ti -1c
.RI "#define \fBRTA_HW_CUSTOM\fP   100"
.br
.ti -1c
.RI "#define \fB__RTA_HW_TYPE\fP   2"
.br
.ti -1c
.RI "#define \fB__RTA_OUT_SIZE_BYTES\fP   256"
.br
.ti -1c
.RI "#define \fB__RTA_OUT_SIZE\fP   (__RTA_OUT_SIZE_BYTES / 4)"
.br
.ti -1c
.RI "#define \fB__RTA_NO_MEM_FLAG\fP   0xCCCCCCCC"
.br
.ti -1c
.RI "#define \fB__RTA_TERM_SUPPORT\fP   1"
.br
.ti -1c
.RI "#define \fB__RTA_TERM_ECHO\fP   0"
.br
.ti -1c
.RI "#define \fB__RTA_TERM_W_BLOCKING\fP   1"
.br
.ti -1c
.RI "#define \fB__RTA_RTX_TASK_SWITCHING\fP   0"
.br
.ti -1c
.RI "#define \fB__IO_RETARGET_ENABLED\fP   1"
.br
.ti -1c
.RI "#define \fB__IO_RETARGET_STREAM_NONE\fP   0"
.br
.ti -1c
.RI "#define \fB__IO_RETARGET_STREAM_RTA\fP   1"
.br
.ti -1c
.RI "#define \fB__IO_RETARGET_STREAM_COM_0\fP   2"
.br
.ti -1c
.RI "#define \fB__IO_RETARGET_STREAM_COM_1\fP   3"
.br
.ti -1c
.RI "#define \fB__IO_RETARGET_STDIO_ROUTE\fP   1"
.br
.ti -1c
.RI "#define \fB__IO_RETARGET_FOPEN_ETC_ENABLED\fP   1"
.br
.ti -1c
.RI "#define \fB__RTA_TERM_IN_SIZE\fP   16"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define __IO_RETARGET_ENABLED   1"
.SS "#define __IO_RETARGET_FOPEN_ETC_ENABLED   1"
.SS "#define __IO_RETARGET_STDIO_ROUTE   1"
.SS "#define __IO_RETARGET_STREAM_COM_0   2"
.SS "#define __IO_RETARGET_STREAM_COM_1   3"
.SS "#define __IO_RETARGET_STREAM_NONE   0"
.SS "#define __IO_RETARGET_STREAM_RTA   1"
.SS "#define __RTA_ENABLED   1"
.SS "#define __RTA_HW_TYPE   2"
.SS "#define __RTA_NO_MEM_FLAG   0xCCCCCCCC"
.SS "#define __RTA_OUT_SIZE   (__RTA_OUT_SIZE_BYTES / 4)"
.SS "#define __RTA_OUT_SIZE_BYTES   256"
.SS "#define __RTA_RTX_TASK_SWITCHING   0"
.SS "#define __RTA_TERM_ECHO   0"
.SS "#define __RTA_TERM_IN_SIZE   16"
.SS "#define __RTA_TERM_SUPPORT   1"
.SS "#define __RTA_TERM_W_BLOCKING   1"
.SS "#define RTA_HW_AT91SAM7Sx   4"
.SS "#define RTA_HW_CUSTOM   100"
.SS "#define RTA_HW_LPC21xx   1"
.SS "#define RTA_HW_LPC23xx   2"
.SS "#define RTA_HW_POLLED   99"
.SS "#define RTA_HW_STR91x   3"
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
