.TH "SDCard" 3 "Sun Jun 26 2011" "Version 1.100.000" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDCard \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSDCard\fP (const char *myname)"
.br
.ti -1c
.RI "void \fBwrite\fP (std::string string)"
.br
.ti -1c
.RI "void \fBappend\fP (std::string string)"
.br
.ti -1c
.RI "void \fBremove\fP (const char *fileName)"
.br
.ti -1c
.RI "void \fBformat\fP (void)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
