.TH "Serial.c" 3 "Sun Jun 19 2011" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serial.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <LPC23xx.H>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBUART1\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSerial_init\fP (void)"
.br
.ti -1c
.RI "int \fBsendchar\fP (int ch)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define UART1"
.SH "Function Documentation"
.PP 
.SS "int sendchar (intch)"
.SS "void Serial_init (void)"
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
