.TH "SerialPort" 3 "Sun Jun 26 2011" "Version 1.100.000" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SerialPort \- 
.PP
class \fBSerialPort\fP: is a class in charge of serial port which is connected to ARM 7 processor.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SerialPort.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerialPort\fP (void)"
.br
.ti -1c
.RI "\fBSerialPort\fP (uint8_t serialPortNo)"
.br
.ti -1c
.RI "void \fBopen\fP (void)"
.br
.ti -1c
.RI "void \fBclose\fP (void)"
.br
.ti -1c
.RI "char \fBreadCharachter\fP (void)"
.br
.ti -1c
.RI "std::string \fBreadLine\fP (char endPoint, bool displayCharachterOnScreenWhileUserIsPressingKeys)"
.br
.ti -1c
.RI "void \fBwrite\fP (charVector charValue, bool newLine)"
.br
.ti -1c
.RI "void \fBwrite\fP (char *charValue, bool newLine)"
.br
.ti -1c
.RI "void \fBwrite\fP (std::string stringValue, bool newLine)"
.br
.ti -1c
.RI "void \fBwrite\fP (int integerValue, bool newLine)"
.br
.ti -1c
.RI "void \fBwrite\fP (float floatValue, int decimalPoint, bool newLine)"
.br
.in -1c
.SH "Detailed Description"
.PP 
class \fBSerialPort\fP: is a class in charge of serial port which is connected to ARM 7 processor. 

.IP "\(bu" 2
UART 0
.IP "\(bu" 2
UART 1 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "SerialPort::SerialPort (void)"Default constructor: Initialize serial port (UART0 by default).
.br
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
