.TH "SerialPort.h" 3 "Sun Jun 19 2011" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SerialPort.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <LPC23xx.H>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSerialPort\fP"
.br
.RI "\fIclass \fBSerialPort\fP: is a class in charge of UART or RS232 or serial port which is connected to ARM 7 processor. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBUART1\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define UART1"
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
