.TH "StopWatch2.cpp" 3 "Sun Jun 19 2011" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StopWatch2.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'StopWatch2.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBStopWatchT2isr\fP (void) __irq"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "TimerManager \fBTMSW2\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void StopWatchT2isr (void)"
.SH "Variable Documentation"
.PP 
.SS "TimerManager \fBTMSW2\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
