.TH "target.c" 3 "Sun Jun 19 2011" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
target.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'LPC23xx.h'\fP
.br
\fC#include 'type.h'\fP
.br
\fC#include 'irq.h'\fP
.br
\fC#include 'target.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTargetInit\fP (void)"
.br
.ti -1c
.RI "void \fBGPIOResetInit\fP (void)"
.br
.ti -1c
.RI "void \fBConfigurePLL\fP (void)"
.br
.ti -1c
.RI "void \fBTargetResetInit\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ConfigurePLL (void)"
.SS "void GPIOResetInit (void)"
.SS "void TargetInit (void)"
.SS "void TargetResetInit (void)"
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
