.TH "TimerEvent2.cpp" 3 "Sun Jun 19 2011" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimerEvent2.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'TimerEvent2.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTimerEventT2isr\fP (void) __irq"
.br
.RI "\fIclass \fBTimerEvent2\fP: is a class which use to execute a task priodicaly on base of the given time there are four timer on ARM7 this class use Timer2 \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "void(* \fBattachedFunction2\fP )(void)"
.br
.ti -1c
.RI "int \fBnumberOfEventOccurrence2\fP = 0"
.br
.ti -1c
.RI "TimerManager \fBTMTE2\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "void(* \fBattachedFunction2\fP)(void)"
.SS "int \fBnumberOfEventOccurrence2\fP = 0"
.SS "TimerManager \fBTMTE2\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
