.TH "TimerEvent3.cpp" 3 "Sun Jun 19 2011" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimerEvent3.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'TimerEvent3.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTimerEventT3isr\fP (void) __irq"
.br
.RI "\fIclass \fBTimerEvent3\fP: is a class which use to execute a task priodicaly on base of the given time there are four timer on ARM7 this class use Timer3 \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "void(* \fBattachedFunction3\fP )(void)"
.br
.ti -1c
.RI "int \fBnumberOfEventOccurrence3\fP = 0"
.br
.ti -1c
.RI "TimerManager \fBTMTE3\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "void(* \fBattachedFunction3\fP)(void)"
.SS "int \fBnumberOfEventOccurrence3\fP = 0"
.SS "TimerManager \fBTMTE3\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
