.TH "Timer0.h" 3 "Wed Jun 15 2011" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Timer0.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <LPC23xx.H>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTimer0\fP"
.br
.RI "\fIclass \fBTimer0\fP: is a class in charge of timer0 of ARM 7 processor \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBOneSecond\fP   11999999"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define OneSecond   11999999"
.PP
Definition at line 3 of file Timer0.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
