.TH "TimerEvent0.cpp" 3 "Sun Jun 19 2011" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimerEvent0.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'TimerEvent0.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTimerEventT0isr\fP (void) __irq"
.br
.RI "\fIclass \fBTimerEvent0\fP: is a class which use to execute a task priodicaly on base of the given time there are four timer on ARM7 this class use Timer0 \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "void(* \fBattachedFunction0\fP )(void)"
.br
.ti -1c
.RI "int \fBnumberOfEventOccurrence0\fP = 0"
.br
.ti -1c
.RI "TimerManager \fBTMTE0\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "void(* \fBattachedFunction0\fP)(void)"
.SS "int \fBnumberOfEventOccurrence0\fP = 0"
.SS "TimerManager \fBTMTE0\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
