.TH "TimerManager" 3 "Sat Jun 18 2011" "Version 1.100.000" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimerManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TimerManager.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimerManager\fP ()"
.br
.ti -1c
.RI "void \fBsetTE0\fP (bool value)"
.br
.ti -1c
.RI "void \fBsetSW0\fP (bool value)"
.br
.ti -1c
.RI "bool \fBgetTE0\fP ()"
.br
.ti -1c
.RI "bool \fBgetSW0\fP ()"
.br
.ti -1c
.RI "void \fBsetTE1\fP (bool value)"
.br
.ti -1c
.RI "void \fBsetSW1\fP (bool value)"
.br
.ti -1c
.RI "bool \fBgetTE1\fP ()"
.br
.ti -1c
.RI "bool \fBgetSW1\fP ()"
.br
.ti -1c
.RI "void \fBsetTE2\fP (bool value)"
.br
.ti -1c
.RI "void \fBsetSW2\fP (bool value)"
.br
.ti -1c
.RI "bool \fBgetTE2\fP ()"
.br
.ti -1c
.RI "bool \fBgetSW2\fP ()"
.br
.ti -1c
.RI "void \fBsetTE3\fP (bool value)"
.br
.ti -1c
.RI "void \fBsetSW3\fP (bool value)"
.br
.ti -1c
.RI "bool \fBgetTE3\fP ()"
.br
.ti -1c
.RI "bool \fBgetSW3\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
EXTRACT_ALL = YES 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TimerManager::TimerManager ()"
.SH "Member Function Documentation"
.PP 
.SS "bool TimerManager::getSW0 ()"
.SS "bool TimerManager::getSW1 ()"
.SS "bool TimerManager::getSW2 ()"
.SS "bool TimerManager::getSW3 ()"
.SS "bool TimerManager::getTE0 ()"
.SS "bool TimerManager::getTE1 ()"
.SS "bool TimerManager::getTE2 ()"
.SS "bool TimerManager::getTE3 ()"
.SS "void TimerManager::setSW0 (boolvalue)"
.SS "void TimerManager::setSW1 (boolvalue)"
.SS "void TimerManager::setSW2 (boolvalue)"
.SS "void TimerManager::setSW3 (boolvalue)"
.SS "void TimerManager::setTE0 (boolvalue)"
.SS "void TimerManager::setTE1 (boolvalue)"
.SS "void TimerManager::setTE2 (boolvalue)"
.SS "void TimerManager::setTE3 (boolvalue)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
