.TH "TimerDelay1.cpp" 3 "Sun Jun 19 2011" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimerDelay1.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'TimerDelay1.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "TimerManager \fBTMTD1\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "TimerManager \fBTMTD1\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
