.TH "type.h" 3 "Sun Jun 19 2011" "Object Oriented Library for ARM 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNULL\fP   ((void *)0)"
.br
.ti -1c
.RI "#define \fBFALSE\fP   (0)"
.br
.ti -1c
.RI "#define \fBTRUE\fP   (1)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBBYTE\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBWORD\fP"
.br
.ti -1c
.RI "typedef unsigned long \fBDWORD\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBBOOL\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define FALSE   (0)"
.SS "#define NULL   ((void *)0)"
.SS "#define TRUE   (1)"
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned int \fBBOOL\fP"
.SS "typedef unsigned char \fBBYTE\fP"
.SS "typedef unsigned long \fBDWORD\fP"
.SS "typedef unsigned short \fBWORD\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Object Oriented Library for ARM 7 from the source code.
